#!/bin/sh
cd build
cd Debug
echo "file attribute adjusting for  RealtekR1000.kext"
sudo chown -R root:wheel RealtekR1000.kext
sudo find RealtekR1000.kext -type d -exec chmod 0755 {} \;
sudo find RealtekR1000.kext -type f -exec chmod 0644 {} \; 

sudo kextunload RealtekR1000.kext

echo "restore file attributes..."
sudo chown -R `whoami` RealtekR1000.kext
sudo kextcache -k /System/Library/Extensions